version: '3.8'

services:
  react:
    container_name: react
    image: 'upcoderk/react-image'
    build:
      context: frontend
      dockerfile: dockerfile
    ports:
      - 3000:3000

  spring:
    container_name: spring
    image: 'upcoderk/myapp'
    build:
      context: backend
      dockerfile: dockerfile
    ports:
      - 8080:8080